version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "develop"
    reviewers:
      - "martines3000"
    assignees:
      - "martines3000"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
